
object Versions {
    const val supportLib = "1.0.2"
    const val legacySupport = "1.0.0"
    const val media = "1.0.1"
    const val constraintLayout = "1.1.3"
    const val recyclerView = "1.0.0"
    const val cardView = "1.0.0"
    const val browser = "1.0.0"
    const val glide = "4.9.0"
    const val rxAndroid = "2.0.2"
    const val daggerCompiler = "2.14.1"
    const val firebaseCore = "16.0.8"
    const val crashlytics = "2.9.9"
    const val paging = "2.1.0"
    const val liveData = "2.0.0"
    const val threeTenAbp = "1.1.0"
    const val kotlinGradlePlugin = "1.3.20"
    const val kotlinStdlibJdk7 = "1.3.20"
    const val gson = "2.8.2"
    const val retrofit = "2.3.0"
    const val gsonConverter = "2.3.0"
    const val rxAdapter = "2.3.0"
    const val room = "2.1.0"
    const val roomCompiler = "2.1.0"
    const val roomRxJava = "1.1.1"
    const val rxJava = "2.1.10"
    const val dagger = "2.14.1"
    const val viewModel = "2.0.0"
    const val lifeCycleExtensions = "2.0.0"
    const val daggerAndroid = "2.23.1"
    const val daggerAndroidSupport = "2.23.1"

}

object Libs {
    // Android
    val supportAppCompatV7 = "androidx.appcompat:appcompat:${Versions.supportLib}"
    val legacySupport = "androidx.legacy:legacy-support-v4:${Versions.legacySupport}"
    val media = "androidx.media:media:${Versions.media}"
    val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    val recyclerView = "androidx.recyclerview:recyclerview:${Versions.recyclerView}"
    val cardView = "androidx.cardview:cardview:${Versions.cardView}"
    val browser = "androidx.browser:browser:${Versions.browser}"
    val paging = "androidx.paging:paging-runtime:${Versions.paging}"
    val liveData = "androidx.lifecycle:lifecycle-livedata:${Versions.liveData}"
    val room = "androidx.room:room-runtime:${Versions.room}"
    val roomCompiler = "androidx.room:room-compiler:${Versions.roomCompiler}"
    val viewModel = "androidx.lifecycle:lifecycle-viewmodel:${Versions.viewModel}"
    val lifecycleExtensions = "androidx.lifecycle:lifecycle-extensions:${Versions.lifeCycleExtensions}"

    // 3rd party
    val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.glide}"
    val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.daggerCompiler}"
    val firebaseCore = "com.google.firebase:firebase-core:${Versions.firebaseCore}"
    val crashlytics = "com.crashlytics.sdk.android:crashlytics:${Versions.crashlytics}"
    val threeTenAbp = "com.jakewharton.threetenabp:threetenabp:${Versions.threeTenAbp}"
    val kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlinGradlePlugin}"
    val gson = "com.google.code.gson:gson:${Versions.gson}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val gsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.gsonConverter}"
    val rxAdapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.rxAdapter}"
    val roomRxJava = "android.arch.persistence.room:rxjava2:${Versions.roomRxJava}"
    val rxJava = "io.reactivex.rxjava2:rxjava:${Versions.rxJava}"
    val kotlinStdlibJdk7 = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlinStdlibJdk7}"
    val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    val daggerAndroid =  "com.google.dagger:dagger-android:${Versions.daggerAndroid}"
    val daggerAndroidSupport = "com.google.dagger:dagger-android-support:${Versions.daggerAndroidSupport}"
}