
object Versions {
    const val supportLib = "28.0.0"
    const val constraintLayout = "1.1.3"
    const val glide = "4.9.0"
    const val rxAndroid = "2.0.2"
    const val daggerCompiler = "2.14.1"
    const val firebaseCore = "16.0.8"
    const val crashlytics = "2.9.9"
    const val paging = "1.0.1"
    const val liveData = "1.1.1"
    const val threeTenAbp = "1.1.0"
    const val kotlinGradlePlugin = "1.3.20"
    const val kotlinStdlibJdk7 = "1.3.20"
    const val gson = "2.8.2"
    const val retrofit = "2.3.0"
    const val gsonConverter = "2.3.0"
    const val rxAdapter = "2.3.0"
    const val room = "1.1.1"
    const val roomCompiler = "1.1.1"
    const val roomRxJava = "1.1.1"
    const val rxJava = "2.1.10"
    const val dagger = "2.14.1"
}

object Libs {
    val supportAppCompatV7 = "com.android.support:appcompat-v7:${Versions.supportLib}"
    val supportV4 = "com.android.support:support-v4:${Versions.supportLib}"
    val supportMediaCompat = "com.android.support:support-media-compat:${Versions.supportLib}"
    val constraintLayout = "com.android.support.constraint:constraint-layout:${Versions.constraintLayout}"
    val recyclerView = "com.android.support:recyclerview-v7:${Versions.supportLib}"
    val cardView = "com.android.support:cardview-v7:${Versions.supportLib}"
    val customTabs = "com.android.support:customtabs:${Versions.supportLib}"
    val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.glide}"
    val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.daggerCompiler}"
    val firebaseCore = "com.google.firebase:firebase-core:${Versions.firebaseCore}"
    val crashlytics = "com.crashlytics.sdk.android:crashlytics:${Versions.crashlytics}"
    val paging = "android.arch.paging:runtime:${Versions.paging}"
    val liveData = "android.arch.lifecycle:livedata:${Versions.liveData}"
    val threeTenAbp = "com.jakewharton.threetenabp:threetenabp:${Versions.threeTenAbp}"
    val kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlinGradlePlugin}"
    val gson = "com.google.code.gson:gson:${Versions.gson}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val gsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.gsonConverter}"
    val rxAdapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.rxAdapter}"
    val room = "android.arch.persistence.room:runtime:${Versions.room}"
    val roomCompiler = "android.arch.persistence.room:compiler:${Versions.roomCompiler}"
    val roomRxJava = "android.arch.persistence.room:rxjava2:${Versions.roomRxJava}"
    val rxJava = "io.reactivex.rxjava2:rxjava:${Versions.rxJava}"
    val kotlinStdlibJdk7 = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlinStdlibJdk7}"
    val dagger = "com.google.dagger:dagger:${Versions.dagger}"
}