package jermaine.domain.articles.model


data class Article(val source: Source = Source(),
                   val author: String = "",
                   val title: String = "",
                   val description: String = "",
                   val url: String = "",
                   val urlToImage: String = "",
                   val publishedAt: String = "") {
    companion object {
        fun getTestData() = """[{"title": "My Article", "description": "My Article Description"}, {"title": "My Article", "description": "My Article Description"}, {"title": "My Article", "description": "My Article Description"}, {"title": "My Article", "description": "My Article Description"}, {"title": "My Article", "description": "My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}, {"title": "My Article", "description": "My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description My Article Description"}]""".trimMargin()
    }
}