name: UI Tests

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'adopt-hotspot'
        cache: gradle

    - name: write keystore.properties file
      env:
        KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      run: |
        printenv KEYSTORE_PROPERTIES
        touch keystore.properties
        echo "$KEYSTORE_PROPERTIES" >> keystore.properties
        cat keystore.properties

    - name: write build.properties file
      env:
        BUILD_PROPERTIES: ${{ secrets.BUILD_PROPERTIES }}
      run: |
        printenv BUILD_PROPERTIES
        touch build.properties
        echo "$BUILD_PROPERTIES" >> build.properties
        cat build.properties
        
    - name: Decode Keystore
      env:
        ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo $ENCODED_KEYSTORE | base64 -di > technews.jks

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
#    - name: Verify Emulator version
#      run: /Users/runner/Library/Android/sdk/emulator/emulator -version

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run UI Tests
      run: ./gradlew nexus5api30DebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

#    - name: Run UI Tests
#      uses: reactivecircus/android-emulator-runner@v2
#      with:
#        api-level: 30
#        profile: Nexus 5
#        emulator-build: 7425822
#        force-avd-creation: false
#        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#        disable-animations: true
#        script: ./gradlew nexus5api30DebugAndroidTest -Pandroid.sdk.channel=3 -Pandroid.testoptions.manageddevices.emulator.gpu=“swiftshader_indirect” -Dorg.gradle.workers.max=1
